<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<NuGetAudit>false</NuGetAudit>
		<NoWarn>NU1903;NU1605</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.OpenApi" Version="1.6.22" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\StudentAcademicManagement.Application\StudentAcademicManagement.Application.csproj" />
		<ProjectReference Include="..\StudentAcademicManagement.Infrastructure\StudentAcademicManagement.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="tessdata\" />
	  <Folder Include="wwwroot\avatars\" />
	  <Folder Include="wwwroot\cccd\" />
	  <Folder Include="wwwroot\documents\" />
	  <Folder Include="wwwroot\special_categories\" />
	</ItemGroup>

</Project>